//
//  LiquidTableViewController.swift
//  BfastBowlBldr
//
//  Created by James Slusser on 9/20/17.
//  Copyright © 2017 James Slusser. All rights reserved.
//

import UIKit

class LiquidTableViewController: UITableViewController, CellProtocol {
    var ingredients = [Ingredient]()
    var selectedIngredients = [Ingredient]()
    let liquidImages = ["AlmondMilk.jpg",
                        "CashewMilk.jpg",
                        "CoconutMilk.jpg",
                        "CoconutWater.jpg",
                        "HempMilk.jpg",
                        "FruitJuice.jpg",
                        "MacadamiaMilk.jpg",
                        "OatMilk.jpg",
                        "RiceMilk.jpg",
                        "Smoothie.jpeg",
                        "SoyMilk.jpg"
    ]
    let liquidNames = ["Almond Milk",
                       "Cashew Milk",
                       "Coconut Milk",
                       "Coconut Water",
                       "Hemp Milk",
                       "Juices",
                       "Macadamia Milk",
                       "Oat Milk",
                       "Rice Milk",
                       "Smoothies",
                       "Soy Milk"
    ]
    let liquidCopy = ["Almond milk is a plant-based alternative to traditional dairy milk. Almond milk is made by grinding almonds and then blending them with filtered water. Some vitamins and minerals are naturally-occurring within the almonds and some are added. There are no artificial colors or flavors added. All brands I've seen state they are made from responsibly-grown almonds and contain no genetically modified organisms (GMOs), but I prefer to make my own.  It's super easy and only contains nuts and water.",
                      "Cashew milk is a non-dairy milk, which means it contains no lactose. In its most basic form, it's made from filtered water and cashews. Cashew milk is easily digested by most folks who are lactose intolerant.",
                      "The coconut fruit, or pulp, is first pressed to release its rich, flavorful cream (it is not the liquid found inside a coconut, as is often mistakenly assumed). Once pressed, the cream is blended with water, vitamins, minerals, thickeners or gums, and sometimes sugar.",
                      "I typically use Coconut Water to dilute whatever nut milk I am using, just to lighten it up a bit.  Add a splash or go for a 50/50 ratio - find whatever works for you.",
                      "Hemp milk, or hemp seed milk, is a plant milk made from hemp seeds that are soaked and ground in water, yielding a beany-nutty cream-flavored substance.",
                      "One morning I was completely out of nut milk, and used Orange Juice as a substitute.  It worked OK for that emerency day, but prefer to use it in combination with other milk.  So now occasionally I will add a splash of whatever juice I have on hand simply to mix things up.",
                      "Macadamia milk is made from macadamia nuts and is a tasty and healthy alternative to soy, oat and almond milks. Macadamia nut milk is rich, smooth and creamy.",
                      "Oat milk is what happens when you soak organic steel cut oats in water, blend the mixture at a high velocity, and then strain it. The result is a creamy, delicious, and dairy-free blend that has just a subtle hint of sweetness and a bit of grainy texture that tastes great on its own, and can be used to enhance a variety of foods.",
                      "Rice milk is a grain milk made from rice. It is mostly made from brown rice and commonly unsweetened. The sweetness in most rice milk varieties is generated by a natural enzymatic process that cleaves the carbohydrates into sugars, especially glucose, similar to the Japanese amazake.",
                      "Similar to my Orange Juice story, one morning I was completely out of nut milk and used a bit of extra smoothie as a substitute.  I really liked it and continue to use it as a treat now and again - use whatever smoothie recipe you like, depending on your mood and ingredients you have on hand.",
                      "Soy milk or soymilk is a plant-based drink produced by soaking and grinding soybeans, boiling the mixture, and filtering out remaining particulates. It is a stable emulsion of oil, water, and protein."
    ]
    let liquidInfo = ["https://en.wikipedia.org/wiki/Almond_milk",
                      "http://www.cookinglight.com/eating-smart/smart-choices/what-is-cashew-milk",
                      "https://en.wikipedia.org/wiki/Coconut_milk",
                      "https://en.wikipedia.org/wiki/Coconut_water",
                      "https://en.wikipedia.org/wiki/Hemp_milk",
                      "https://en.wikipedia.org/wiki/Juice",
                      "https://www.diabetichealthclinic.org/macadamia-nut-milk/",
                      "https://www.livestrong.com/article/267017-what-are-the-benefits-of-oat-milk/",
                      "https://en.wikipedia.org/wiki/Rice_milk",
                      "https://en.wikipedia.org/wiki/Smoothie",
                      "https://en.wikipedia.org/wiki/Soy_milk"
    ]
    let liquidPurch = ["https://amzn.to/2uRhEPc", // Almond Milk
        "https://amzn.to/2qdhKeD", // Cashew Milk
        "https://amzn.to/2GzrkDo", // Coconut Milk
        "https://amzn.to/2Hgviy5", // Coconut Water
        "https://amzn.to/2q7FDnK", // Hemp Milk
        "https://amzn.to/2HbrJZK", // Fruit Juice
        "https://amzn.to/2q9oB8y", // Macadamia Milk
        "https://amzn.to/2uJPgyg", // Oat Milk
        "https://amzn.to/2JnVqr4", // Rice Milk
        "https://amzn.to/2GDbTWE", // Smoothie Mix
        "https://amzn.to/2GzDegt" // Soy Milk
    ]
    func switchButtonTapped(WithStatus status: Bool, ForCell myCell: IngredientCell) {
        guard let indexPath = self.tableView.indexPath(for: myCell) else { return }
        print("cell at indexpath \(String(describing: indexPath)) tapped with switch status \(status)")
        let liquidSwitchSelected = myCell.label.text!
        print("Liquid added/removed was \(String(describing: liquidSwitchSelected))")
        if status {
            selectedIngredients.append(ingredients[indexPath.row])
        } else {
            guard let index = selectedIngredients.index(where: { $0.name == ingredients[indexPath.row].name }) else { return }
            selectedIngredients.remove(at: index)
        }
    }
    @IBAction func liquidSelected(_ sender: UIButton) {
    }
    override func viewDidLoad() {
        super.viewDidLoad()
        for i in 0 ..< liquidCopy.count {
            let newIngredient = Ingredient(name: liquidNames[i],
                                           imageString: liquidImages[i],
                                           copy: liquidCopy[i],
                                           info: liquidInfo[i],
                                           purchaseURL: liquidPurch[i],
                                           type: .liquid)
            ingredients.append(newIngredient)
        }
        let ingredientNib = UINib(nibName: "IngredientCell", bundle: nil)
        tableView.register(ingredientNib, forCellReuseIdentifier: "IngredientCell")
        tableView.estimatedRowHeight = 50
        // for inregedient in selectedIngredients {
        //   print(inregedient.name)
    }
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    // MARK: - Table view data source
    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return liquidNames.count
    }
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "IngredientCell", for: indexPath) as! IngredientCell
        let row = indexPath.row
        cell.configure(textForLabel: ingredients[row].name, image: ingredients[row].imageString, setDelegate: self)
        return cell}
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        performSegue(withIdentifier: "ShowLiquidDetails", sender: indexPath.row)
    }
    override func shouldPerformSegue(withIdentifier identifier: String, sender: Any?) -> Bool {
        switch identifier {
        case "SelectAddIn":
            guard selectedIngredients.contains(where: {$0.type == .liquid}) else {
                let alert = UIAlertController(title: "Bowl Builder Tip", message: "Please select at least one Liquid before continuing", preferredStyle: UIAlertControllerStyle.alert)
                alert.addAction(UIAlertAction(title: "OK", style: UIAlertActionStyle.default, handler: nil))
                present(alert, animated: true, completion: nil)
                return false
            }
        default:
            break
        }
        return true
    }
    // MARK: - Navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "ShowLiquidDetails" {
            let detailViewController = segue.destination as! IngredientDetailViewController
            guard let row = sender as? Int else { fatalError("Unable to cast sender as Int")}
            detailViewController.ingredientDetailImages = liquidImages[row]
            detailViewController.ingredientAddlCopy = liquidCopy[row]
            detailViewController.ingredientMoreInfo = liquidInfo[row]
            detailViewController.ingredientPurchase = liquidPurch[row]
        }
        if segue.identifier == "SelectAddIn" {
            //   print (selectedIngredients)
            // You previously had the segue destination view controller being cast as the IngredientTableViewController instead of
            // LiquidTableViewController.
            let AddInTableViewController = segue.destination as! AddInTableViewController
            AddInTableViewController.selectedIngredients = selectedIngredients
        }
    }
}
